### ISSUE TITLE
Add anti-glide animation feature

### ISSUE THREAD

**Issue by Whyshchuck** [mapedorr/popochiu#101]
It would be nice to add an option for characters to run his animation in anti-glade mode like.

How it work - if anti-glade is on chaa=racter's sprite cheneges its position only when new walking cycles' frame is displayed.
It avoids sprite movement between frames - avoids effect of gliding.

It would work like AGS method ```Character.MovementLinkedToAnimation```
https://adventuregamestudio.github.io/ags-manual/Character.html?highlight=glide&case_sensitive=0#charactermovementlinkedtoanimation

Why it is important and when it is necessary:
If you have sharp eye, you would find it necessary in every game, where:
- walking cycle FPS is lower than game's FPS and
- distance traveled by character beetween frames is bigger than 1 pixel.

In effect it will be most important in low res games with low fps animations

Below short animation illustrating anti-glide in action (walking cycle is not perfect but I've slowed down animation and characters movement to make it more illustrous)

https://github.com/mapedorr/popochiu/assets/34949896/85dc9385-e873-4b49-a97d-167e756be09a

**Comment by mapedorr** [comment]
I think this can be a must have for the plugin. And as you already made some progress on the code necessary to make it work, we could think about adding it to v2 release.
