### ISSUE TITLE
Leverage GDScript 2.0 features to make scripting more robust

### ISSUE THREAD

**Issue by stickgrinder** [mapedorr/popochiu#15]
`E.Run()` implementation made its way into Popochiu to avoid the convolutions of _yielding_ the execution of coroutines and processing the necessary signals.

Godot 4.0 will introduce a new version of GDScript with the very convenient `await` keyword. The syntax still involves starting a coroutine **then** _await_ for the signal (see https://www.reddit.com/r/godot/comments/sbhvmh/godot_40_await_function/), but  Popochiu's API functions can serve some syntactic sugar to allow something like:

```gdscript
await C.Say("Player", "I guess the game will wait for me to finish this Nolan-inspired line of dialogue...")
```

Put like that, having blocking functions return the proper signal should suffice, but it may require a pervasive redesign of the public framework API. That's why this issue is marked as epic.

**Comment by mapedorr** [comment]
Finally... the release of [v2.0-alpha1](https://github.com/mapedorr/popochiu/tree/v2.0-alpha1) handles this.
