### ISSUE TITLE
Error on running project

### ISSUE THREAD

**Issue by mefjak** [mapedorr/popochiu#48]
2.0 Alpha on MacOS M1 :

After adding simple room and character there is an error on popochiu.gd script line 672 : `Parser Error: Cannot infer the type of "character" variable because the value doesn't have a set type.`

<img width="1465" alt="Zrzut ekranu 2023-04-17 o 15 12 43" src="https://user-images.githubusercontent.com/22888465/232494342-fe417b07-abfb-4fb6-bacd-97ffd0158919.png">

I think it could be related to naming character '01'

**Comment by mapedorr** [comment]
Fixed with https://github.com/mapedorr/popochiu/pull/63
