### ISSUE TITLE
[2.0] Type cast failing for AudioCue on play

### ISSUE THREAD

**Issue by DarioMazzanti** [mapedorr/popochiu#53]
Hi! Thanks for the cool project! It's really nice to use and the tutorials are relaxing as well.

**Error**

I am getting the following error while playing a popochiu project:

`Trying to assign value of type 'Resource' to a variable of type 'audio_cue.gd'.`

I am not particularly familiar with Godot -could this be a typecast failing at line 31 of `audio_manager.gd` ?
That's where the error is happening.
I tried changing the type of variable ac to Resource, and then add a cast later, to set the volume (as AudioCue) but that is failing as well.

**Steps to reproduce:**

1. add sfx file to project (e.g. following popochiu tutorial, using sfx_toy_car sample
2. play project
3. get the error

**Running on**
- Popochiu v2.0-alpha1
- Godot v4.0.3.stable.official [5222a99f5]

**Comment by mapedorr** [comment]
Thanks. We'll give it a look.

**Comment by mapedorr** [comment]
@DarioMazzanti I fixed the bug in branch [fix/53-type_cast_fail](https://github.com/mapedorr/popochiu/tree/fix/53-type_cast_fail) . I made a test and it worked. But if you want, and I would appreciate it, you can verify it.

**Comment by DarioMazzanti** [comment]
Hi! I just cloned and checked the fixed branch - I can ear sounds from the demo scene, and the error message is not there anymore. 
Thanks so much!
