### ISSUE TITLE
Add offset parameter to PopochiuCharacter.walk_to functions

### ISSUE THREAD

**Issue by mapedorr** [mapedorr/popochiu#69]
As @vonagam suggested in #68 .

Add an `offset: Vector2` parameter to `walk_to_clicked` , `walk_to_prop` , `walk_to_hotspot` , `walk_to_marker` in **PopochiuCharacter**. It will make sense when moving multiple characters since "it makes sense to place them not at the same exact position".

**Comment by vonagam** [comment]
What scale should be applied to such offsets?
a) a target's scale (clicked/prop/hotspot/marker).
b) a current room's sclae.
c) no scale, the offset is expected to be global value.

**Comment by mapedorr** [comment]
I think option C is the better one. While it may eventually be necessary to consider the scale of destiny, I'm not sure.
