### ISSUE TITLE
queued actions not working as expected

### ISSUE THREAD

**Issue by papernoise** [mapedorr/popochiu#78]
**Godot version**: 4.1.1

**Popochiu Version**: 2.0 alpha

**OS**: Windows 11

## Expected behaviour:

I am expecting this to work the way it's explained on the v2 release notes, for example:

```gdscript
func _on_click() -> void:
    await C.walk_to_clicked()
    await C.face_clicked()
```

## What happens instead

When typing the code as shown above, none of the lines in the` _on_click() function _` are executed. This can be quickly tested by adding a dialog line, for example:

```gdscript
func _on_click() -> void:
        C.walk_to_clicked()
        C.face_clicked()
        "Player: Can't open it, but well... who cares about windows anyway. I'll use the door."
```

In this case the character just walks to the prop, like when clicking on an empty spot, and the dialog line is not spoken by the character.

## Current workarounds

To make it work I have to put everything inside the `E.queue` function
For example, this works:

```gdscript
func _on_click() -> void:
    E.queue([
       await C.walk_to_clicked(),
       await C.face_clicked()
    ]) 
```

But it's not perfect. If I add dialog options, these are always executed last, even if I put them first in the queue
To get Popochiu to repsect the order in the queue I need to write the code like this, i.e. by remiving `await `and appenting `queue_` instead

```gdscript
func _on_click() -> void:
    E.queue([
      'Player: dialog line',
       C.queue_walk_to_clicked(),
       C.queue_face_clicked()
    ])
```

**Comment by mapedorr** [comment]
In this code example you have to add `await` before the first two lines, and at the moment is not possible to make characters to talk just by typing the string:

```
func _on_click() -> void:
	C.walk_to_clicked()
	C.face_clicked()
	"Player: Can't open it, but well... who cares about windows anyway. I'll use the door."
```

There are two ways to achieve this.

1. The one we want to promote thanks to Godot 4's `await`:

```
func _on_click() -> void:
	await C.walk_to_clicked()
	await C.face_clicked()
	await C.player.say("Can't open it, but well... who cares about windows anyway. I'll use the door.")
```

2. Using the method to queue instructions created for Popochiu version 1 (which is the one you used in your last code example):

```
func _on_click() -> void:
	E.queue([
		C.queue_walk_to_clicked(),
		C.queue_face_clicked(),
		"Player: Can't open it, but well... who cares about windows anyway. I'll use the door."
	])
```

In this video you can see both code examples working:

https://github.com/mapedorr/popochiu/assets/4536477/3042f567-7fa3-498a-b2ed-5a0a1e3c4aa8
