### ISSUE TITLE
Cannot move WalkToHelper with mouse

### ISSUE THREAD

**Issue by papernoise** [mapedorr/popochiu#80]
**Godot version**: 4.1.1
**Popochiu Version**: 2.0 alpha
**OS**: Windows 11

## How to reproduce
- Select a prop
- click the "Walk to point" button
- use either the Move or Select tool (same results with both) to move the WalkToHelper

What happens is that the whole prop moves, not just the WalkToHelper

here's a quick screen recording:

https://github.com/mapedorr/popochiu/assets/1595523/2f3126f6-6f30-420f-8dfe-9b65ddf8bc29

**Comment by mapedorr** [comment]
This is something that started happening in Godot 4.1. It is probably something we have to fix since it also happens in Godot v4.2.dev5.official.

**Comment by papernoise** [comment]
Great! The workaround for now is to manually change the coordinates in the Transform section btw.

**Comment by mapedorr** [comment]
Fixed in 4b1317eabbaadaf7190496a66a7ca86e9f0d3734
