### ISSUE TITLE
Character doesn't follow player

### ISSUE THREAD

**Issue by BenjaTK** [mapedorr/popochiu#84]
Even if follow_player is set to true, my character won't follow them. If you find it, could you send me the fix here? I'm making a game for a game jam and I need it fixed.

**Comment by mapedorr** [comment]
Hey @BenjaTK ! While the property is there, I've never implemented anything to make that functionality available. It's something I haven't had time to work on yet. (-_＼)

＿φ( °-°)/  Still... If you're using Popochiu 2.0, there might be a workaround by doing something like `C.TheNPCName.walk_to(get_local_mouse_position() + _some_offset)`. Or if the character is moving to a prop or a hotspot, you could do something like `C.TheNPCName.walk_to_prop("TheProp", _some_offset)`.

**Comment by BenjaTK** [comment]
Thanks a lot! That worked perfectly!

**Comment by mapedorr** [comment]
@JuannFerrari Added this feature in #105 .

**Comment by stickgrinder** [comment]
This is a duplicate of #122
