### ISSUE TITLE
Issues with playing multiple sound effects

### ISSUE THREAD

**Issue by papernoise** [mapedorr/popochiu#88]
Godot: 4.1.2
Popochiu: 2.0 (latest version from 2.0 branch)

How to reproduce:

- add code to multiple props to play sound effects
- test the game and click the props so the sounds play overlapping each other
- Debugger shows error messages
- the issue does not appear when playing sfx on top of music, haven't tested with voices or UI sounds.

These are the errors:
> E 0:00:07:0836   audio_manager.gd:229 @ _play(): Signal 'finished' is already connected to given callable 'Node(audio_manager.gd)::_make_available' in that object.
  <C++ Error>    Method/function failed. Returning: ERR_INVALID_PARAMETER
  <C++ Source>   core/object/object.cpp:1294 @ connect()
  <Stack Trace>  audio_manager.gd:229 @ _play()
                 audio_manager.gd:56 @ play_sound_cue()
                 audio_cue_sound.gd:15 @ play()
                 prop_cred_anta_dx.gd:16 @ _on_click()
                 popochiu_clickable.gd:64 @ _unhandled_input()

**Comment by mapedorr** [comment]
Fixed in 88044a2cf182f5b1b121749fde49e6e62640767c. Now new AudioStreamPlayer (or AudioStreamPlayer2D) are created when the system runs out of players (that is when all the created players by default are in use).
