### ISSUE TITLE
Audio cues: can't change pitch setting

### ISSUE THREAD

**Issue by papernoise** [mapedorr/popochiu#89]
Godot: 4.1.2
Popochiu: 2.0 (latest version from 2.0 branch)

## How to reproduce:
- go to the Audio tab in the Popochiu dock
- click an audio file (I have tested this with music and sfx)
- note that the pitch displays an odd default value like 1.063, but never the expected value of 1.0 
- clicking the number field and entering a new value has no effect
- You can click and drag the number, and it will accept the change, but it's a bit cumbersome

**Comment by mapedorr** [comment]
Fixed in 4b1317eabbaadaf7190496a66a7ca86e9f0d3734.
