### ISSUE TITLE
Popochiu complains about Aesprite missing, even if Aesprite importer is not being used.

### ISSUE THREAD

**Issue by papernoise** [mapedorr/popochiu#90]
Godot: 4.1.2
Popochiu: 2.0 (latest version from 2.0 branch)

# How to reproduce:

- Create a new Godot project
- Add and enable Popochiu
- See this error message below in the Output

> res://addons/popochiu/editor/importers/aseprite/docks/animation_player_inspector_dock.gd:60 - Invalid call. Nonexistent function 'get' in base 'Nil'.
 Aseprite command failed. Please, check if the right command is in your PATH or configured through "Editor Settings > Popochiu > Import > Command Path".

I don't get this for the project I had started with 2.0 Alpha 1 and which I have updated to the latest 2.0 branch.

**Comment by stickgrinder** [comment]
Solved this working on #37 for both rooms and characters.
Will be in next 2.0 version.
