### ISSUE TITLE
Errors when creating new room or character

### ISSUE THREAD

**Issue by papernoise** [mapedorr/popochiu#91]
Godot: 4.1.2
Popochiu: 2.0 (latest version from 2.0 branch)

## How to reproduce

- Create new Godot project and add/enable Popochiu
- Create a new room or a new character
- The room or the character are being created, but this error message is being displayed:

>   gdscript://-9223369853098720981.gd:7 - Parse Error: Preload file "gdscript://character_state_template.gd" does not exist.
  gdscript://-9223369853098720981.gd:7 - Parse Error: Cannot infer the type of "Data" constant because the value doesn't have a set type.
  gdscript://-9223369853098720981.gd:9 - Parse Error: "Data" is a constant but does not contain a type.

**Comment by stickgrinder** [comment]
This problem seems to be solved on 4.2 that will be the target release version.
I tested it on a brand new project with 2.0 branch and it works without errors.

Closing for now.
