### ISSUE TITLE
A global option to scale up pixel graphics?

### ISSUE THREAD

**Issue by shaunabanana** [mapedorr/popochiu#93]
As the title suggests, currently the imported sprites (both images textures and Aseprite files) stays at 1x scale while the GUI responds to the "scale GUI" option. It could be very helpful for pixel games to allow setting a global pixel scale.

**Comment by stickgrinder** [comment]
@shaunabanana can you elaborate a bit more on that? We are not sure we understand what you are experiencing (and expecting).

**Comment by mapedorr** [comment]
We can change the names if the current ones aren't entirely clear. Maybe something like Base size and Play size?

**Comment by shaunabanana** [comment]
Yes, that would be much clearer! Thank you!

**Comment by stickgrinder** [comment]
To make thing clear to newcomers we can be a bit more pedantic and write `Native game resolution` and `Playing window resolution` maybe?

Resolution or size may both work, probably.

**Comment by mapedorr** [comment]
I'm going to use the labels you suggest @stickgrinder . That change will be in #100 branch.
