### ISSUE TITLE
Walk sounds: Can't stop the sound

### ISSUE THREAD

**Issue by papernoise** [mapedorr/popochiu#94]
Godot: 4.1.2
Popochiu: 2.0 (latest version from 2.0 branch)

## How to reproduce

play an sfx inside the character's `_play_walk()` function
eg.: `A.sfx_steps.play()`

add `A.sfx_steps.stop()` to the character's `_play_idle()` function. This should stop the walk sound once the character enters the "idle" state.

## Issue:

Audio keeps playing and isn't being stopped.

**Comment by mapedorr** [comment]
Fixed in c3d785ab81025571f26dadda4ebb6e4242c7df2f. Will be part of Alpha 5.
