### ISSUE TITLE
Audio Issue - Crashes due to Invalid get index

### ISSUE THREAD

**Issue by SoneaB** [mapedorr/popochiu#98]
Seems to be something screwy going on in audio manager.  Keep getting issues even on files that have already been used multiple times in the scene. Seems random as to which file or type of file triggers this or how many times it will play before it decides it can no longer find it. Had it happen with sfx_ and vo_ files though not so far with mx_ files. 

Invalid get index 'vo_goddiu_02' (on base: 'Dictionary')

E 0:00:16:0070   audio_manager.gd:230 @ _play(): Signal 'finished' is already connected to given callable 'Node(audio_manager.gd)::_make_available' in that object.
  <C++ Error>    Method/function failed. Returning: ERR_INVALID_PARAMETER
  <C++ Source>   core/object/object.cpp:1294 @ connect()
  <Stack Trace>  audio_manager.gd:230 @ _play()
                 audio_manager.gd:57 @ play_sound_cue()
                 audio_cue_sound.gd:15 @ play()
                 popochiu_character.gd:236 @ say()
                 popochiu.gd:708 @ _eval_string()
                 popochiu.gd:217 @ queue()
                 popochiu.gd:1336671456 @ _eval_string()
                 popochiu_character.gd:1336668832 @ say()
                 graphic_interface.gd:76 @ _continue()

Popochiu v2.0.0
Godot 4.1.1

**Comment by mapedorr** [comment]
I'm gonna close this since it is related with #88 .
