### ISSUE TITLE
Crash when using camera_zoom

### ISSUE THREAD

**Issue by SoneaB** [mapedorr/popochiu#99]
Zooming works but as soon as you try to zoom back to the original position it causes a crash.

Invalidcall. Nonexistent function 'isplaying_queue' in base Tween

Tried this a few ways both during conversations/sequences and by triggering by exiting/entering a region. I wanted to make sure that it still crashed even after I was sure the tween should have finished. 

Does not log an error but does point here

func camera_zoom(target := Vector2.ONE, duration := 1.0) -> void:
	if is_instance_valid(_tween) and _tween.isplaying_queue():
		_tween.kill()
	
	_tween = create_tween()
	_tween.tween_property(main_camera, 'zoom', target, duration)\
	.from_current().set_trans(Tween.TRANS_SINE).set_ease(Tween.EASE_OUT)
	
	await _tween.finished

Godot 4.1.1
Popochiu v2.0.0

**Comment by mapedorr** [comment]
Fixed in 88044a2cf182f5b1b121749fde49e6e62640767c
